#ifndef DXFEED_NATIVE_SRC_LIBS_API_INCLUDE_API_EVENTTYPES_H_
#define DXFEED_NATIVE_SRC_LIBS_API_INCLUDE_API_EVENTTYPES_H_

#include <cstdint>

enum class EventType : int32_t {
  Quote
};

#endif //DXFEED_NATIVE_SRC_LIBS_API_INCLUDE_API_EVENTTYPES_H_
