#
# Project options
#

set(DEFAULT_PROJECT_OPTIONS "")
#set(DEFAULT_PROJECT_OPTIONS ${DEFAULT_PROJECT_OPTIONS} ${GENERIC_PROJECT_OPTIONS})
set(DEFAULT_PROJECT_OPTIONS ${DEFAULT_PROJECT_OPTIONS}
        POSITION_INDEPENDENT_CODE ON
        LINKER_LANGUAGE "CXX"
        )


#
# Include directories
#

set(DEFAULT_INCLUDE_DIRECTORIES "")
#set(DEFAULT_INCLUDE_DIRECTORIES ${DEFAULT_INCLUDE_DIRECTORIES} ${GENERIC_INCLUDE_DIRECTORIES})


#
# Libraries
#

set(DEFAULT_LIBRARIES "")
#set(DEFAULT_LIBRARIES ${DEFAULT_LIBRARIES} ${GENERIC_LIBRARIES})


#
# Compile definitions
#

set(DEFAULT_COMPILE_DEFINITIONS "")
#set(DEFAULT_COMPILE_DEFINITIONS ${DEFAULT_COMPILE_DEFINITIONS} ${GENERIC_COMPILE_DEFINITIONS})


#
# Compile options
#

set(DEFAULT_COMPILE_OPTIONS "")
#set(DEFAULT_COMPILE_OPTIONS ${DEFAULT_COMPILE_OPTIONS} ${GENERIC_COMPILE_OPTIONS})


#
# Linker script
#
set(DEFAULT_LINKER_SCRIPT "")
#set(DEFAULT_LINKER_SCRIPT ${DEFAULT_LINKER_SCRIPT} ${GENERIC_LINKER_SCRIPT})


#
# Linker options
#

set(DEFAULT_LINKER_OPTIONS "")
#set(DEFAULT_LINKER_OPTIONS ${DEFAULT_LINKER_OPTIONS} ${GENERIC_LINKER_OPTIONS} ${DEFAULT_LINKER_SCRIPT})